name: Create Blocklet
title: Create Blocklet
description: Bootstrap a blocklet within seconds
theme: docs
github: https://github.com/blocklet/create-blocklet
plugins:
  - resolve: '@xmark/plugin-docs-indexer'
optimizeDeps:
  include:
    - docs-searchbar.js
themeConfig:
  colors:
    primary: '#25C99B'
  sidebar:
    en:
      - text: Welcome
        link: /
      - text: Quick Start
        link: /quick-start
        items:
          - text: Setup Node.js
            link: /quick-start/nodejs
          - text: Setup DID Wallet
            link: /quick-start/did-wallet
          - text: Instal Blocklet CLI
            link: /quick-start/blocklet-server
          - text: Create first blocklet
            link: /quick-start/hello-blocklet
      - text: How To Guides
        items:
          - text: Create single blocklet
            link: /how-to/create-single-blocklet
          - text: Create composition blocklet
            link: /how-to/create-blocklet-composition
          - text: Customize your blocklet
            link: /how-to/customize-blocklet
          - text: Manage blocklet release
            link: /how-to/manage-blocklet-release
          - text: Add new template
            link: /how-to/add-new-template
          - text: Where to go from here?
            link: /how-to/further-resources
      - text: Reference Guides
        items:
          - text: Blocklet folder structure
            link: /reference/blocklet-structure
          - text: Composition folder structure
            link: /reference/composition-structure
          - text: Available npm scripts
            link: /reference/npm-scripts
      - text: Templates
        link: /templates
      - text: Frequently Asked Questions
        link: /faq
    zh:
      - text: 欢迎
        link: /
      - text: 新手入门
        link: /quick-start
        items:
          - text: 设置 Node.js
            link: /quick-start/nodejs
          - text: 设置 DID Wallet
            link: /quick-start/did-wallet
          - text: 安装 Blocklet CLI
            link: /quick-start/blocklet-server
          - text: 创建第一个 Blocklet
            link: /quick-start/hello-blocklet
      - text: 操作手册
        items:
          - text: 创建单个应用
            link: /how-to/create-single-blocklet
          - text: 创建组合应用
            link: /how-to/create-blocklet-composition
          - text: 自定义你的应用
            link: /how-to/customize-blocklet
          - text: 应用版本管理
            link: /how-to/manage-blocklet-release
          - text: 添加应用模板
            link: /how-to/add-new-template
          - text: 更多开发资源
            link: /how-to/further-resources
      - text: 参考指南
        items:
          - text: 单应用目录结构
            link: /reference/blocklet-structure
          - text: 组合应用的目录结构
            link: /reference/composition-structure
          - text: 可用的脚本
            link: /reference/npm-scripts
      - text: 模板列表
        link: /templates
      - text: 常见问题
        link: /faq
