name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Init
        run: make github-init

      - name: Deploy
        env:
          GIT_HUB_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
          BLOCKLET_REGISTRY: ${{ secrets.BLOCKLET_REGISTRY }}
          BLOCKLET_REGISTRY_SK: ${{ secrets.ABTNODE_DEV_SK }}
        run: bash ./tools/publish.sh

      - name: Release to Github
        uses: blocklet/action-release-to-github@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
