---
name: "🚀 Feature"
description: Start a feature request 
title: "[Feature]: Feature title"
labels: [feature]
assignees: []
body:
  - type: textarea
    id: Why
    attributes:
      label: Why you want this Feature?
      description: What is the usage scenario? 
    validations:
      required: true
  - type: textarea
    id: Use
    attributes:
      label: Describe the solution you'd like
      description: How to use it?
  - type: textarea
    id: additional
    attributes:
      label: Additional context
