name: 'Lint PR Title'

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master
      - dev

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      - uses: ArcBlock/action-lint-pull-request-title@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
