name: Create Blocklet
title: Create Blocklet
description: Bootstrap a blocklet within seconds
theme: docs
github: https://github.com/blocklet/create-blocklet
themeConfig:
  colors:
    primary: '#1DC1C7'

# 删除 screenshots, blocklet.md, 更新 blocklet.yml 、readme.md
# 需要在所有 pages 项目中把 theme 从内置主题切换为 arcblock 主题：