name: Deploy Page Site

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # - uses: pnpm/action-setup@v3
      #   with:
      #     version: 9
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #     cache: 'pnpm'

      # - run: npm add -g @antfu/ni
      # - run: nci

      # - name: Deploy to Blocklet Server
      #   uses: blocklet/action-workflow@v1
      #   with:
      #     skip-deps: false
      #     skip-bundle: false
      #     skip-upload: true
      #     skip-deploy: false
      #     skip-release: true
      #     deploy-app-did: zNKkQuRidtsBVskb8oDXKVh5PpM5uD5PKxim
      #     deploy-mount-point: /
      #     bundle-command: nr bundle
      #     working-directory: website/pages
      #     server-endpoint: ${{ secrets.XMARK_NODE_ENDPOINT }}
      #     server-access-key: ${{ secrets.XMARK_NODE_ACCESS_KEY }}
      #     server-access-secret: ${{ secrets.XMARK_NODE_ACCESS_SECRET }}
      #     slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
