name: Deploy Docs Site

on: workflow_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip actions]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: npm add -g @antfu/ni
      - run: nci

      - name: Deploy to Blocklet Server
        uses: blocklet/action-workflow@v1
        with:
          skip-deps: false
          skip-bundle: false
          skip-upload: true
          skip-deploy: false
          skip-release: true
          bundle-command: nr bundle
          deploy-app-did: z8iZuvjcXn3Lj1DXsaKkAPvL4y1nf5SSsUsXc
          deploy-mount-point: docs
          working-directory: packages/docs-site
          server-endpoint: ${{ secrets.AWS_NODE_ENDPOINT }}
          server-access-key: ${{ secrets.AWS_NODE_ACCESS_KEY }}
          server-access-secret: ${{ secrets.AWS_NODE_ACCESS_SECRET }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
