name: Npm publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Config Git
        run: |
          git config --local user.name "bot"
          git config --local user.email "bot@arcblock.io"
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - run: npm add -g @antfu/ni
      - run: nci

      - name: Publish to npm
        run: |
          npm config set '//registry.npmjs.org/:_authToken' "${{ secrets.NPM_TOKEN }}"
          pnpm -r publish --access public --no-git-checks

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Release
        run: |
          git tag -a ${{ steps.package-version.outputs.current-version}} -m "Release ${{ steps.package-version.outputs.current-version}}. Revision is: $(GIT_VERSION)" | true
          git push origin ${{ steps.package-version.outputs.current-version}} | true
